spring.application.name=bookShows
spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
management.endpoint.health.show-details=always
